// Auto-generated by openapi-typescript
// Do not make direct changes to the file.

export type paths = {
  "/api/material-geraete": {
    get: {
      operationId: "getAllEquipment";
      responses: {
        200: {
          content: {
            "application/json": {
              schema: {
                type: "array";
                items: {
                  $ref: "#/components/schemas/EquipmentResponse";
                };
              };
            };
          };
        };
      };
    };
    post: {
      operationId: "createEquipment";
      requestBody: {
        content: {
          "application/json": {
            schema: {
              $ref: "#/components/schemas/CreateEquipmentRequest";
            };
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/EquipmentResponse";
              };
            };
          };
        };
      };
    };
  };
  "/api/material-geraete/{id}": {
    get: {
      operationId: "getEquipmentById";
      parameters: {
        path: {
          id: {
            schema: {
              type: "string";
              format: "uuid";
            };
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              schema: {
                $ref: "#/components/schemas/EquipmentResponse";
              };
            };
          };
        };
      };
    };
    delete: {
      operationId: "deleteEquipment";
      parameters: {
        path: {
          id: {
            schema: {
              type: "string";
              format: "uuid";
            };
          };
        };
      };
      responses: {
        204: {
          description: "No Content";
        };
      };
    };
  };
  "/api/material-geraete/search": {
    get: {
      operationId: "searchEquipment";
      parameters: {
        query: {
          name?: {
            schema: {
              type: "string";
            };
          };
          serialNumber?: {
            schema: {
              type: "string";
            };
          };
          storageLocation?: {
            schema: {
              type: "string";
            };
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              schema: {
                type: "array";
                items: {
                  $ref: "#/components/schemas/EquipmentResponse";
                };
              };
            };
          };
        };
      };
    };
  };
};

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    EquipmentResponse: {
      id: string;
      name: string;
      serialNumber: string;
      type: string;
      storageLocation: string;
      description?: string;
      acquisitionDate?: string;
      manufacturer?: string;
    };
    CreateEquipmentRequest: {
      name: string;
      serialNumber: string;
      type: string;
      storageLocation: string;
      description?: string;
      acquisitionDate?: string;
      manufacturer?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type operations = {
  getAllEquipment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EquipmentResponse"][];
        };
      };
    };
  };
  createEquipment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateEquipmentRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EquipmentResponse"];
        };
      };
    };
  };
  getEquipmentById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EquipmentResponse"];
        };
      };
    };
  };
  deleteEquipment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        content?: never;
      };
    };
  };
  searchEquipment: {
    parameters: {
      query: {
        name?: string;
        serialNumber?: string;
        storageLocation?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EquipmentResponse"][];
        };
      };
    };
  };
};
