/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle Mitglieder auflisten */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mitglied anhand der ID laden */
        get: operations["getMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle Standorte auflisten */
        get: operations["listLocations"];
        put?: never;
        /** Neuen Standort anlegen */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Standort anhand der ID laden */
        get: operations["getLocation"];
        /** Standort vollständig aktualisieren */
        put: operations["updateLocation"];
        post?: never;
        /** Standort löschen */
        delete: operations["deleteLocation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{memberId}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mitglied einem Standort zuweisen */
        post: operations["assignMemberToLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /**
             * @description Maschinenlesbarer Error-Code
             * @example VALIDATION_FAILED
             */
            error?: string;
            /**
             * @description Menschenlesbare Beschreibung
             * @example Die Anfrage enthält ungültige Felder.
             */
            message?: string;
            details?: {
                field?: string;
                message?: string;
            }[];
        };
        PaginationMeta: {
            /** @example 0 */
            page?: number;
            /** @example 20 */
            size?: number;
            /** @example 100 */
            totalElements?: number;
            /** @example 5 */
            totalPages?: number;
        };
        LocationResponse: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /** @example Hauptwache */
            name?: string;
            /** @example Hauptstraße 1, 50667 Köln */
            address?: string;
            /**
             * @example FIRE_STATION
             * @enum {string}
             */
            type?: "FIRE_STATION" | "EQUIPMENT_DEPOT" | "TRAINING_CENTER";
        };
        MemberResponse: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /** @example Max */
            firstName?: string;
            /** @example Mustermann */
            lastName?: string;
            /** @example Hauptbrandmeister */
            rank?: string;
            /** @example Einsatzabteilung */
            unit?: string;
            locations?: components["schemas"]["LocationResponse"][];
        };
        CreateLocationRequest: {
            /** @example Hauptwache */
            name: string;
            /** @example Hauptstraße 1, 50667 Köln */
            address?: string;
            /**
             * @example FIRE_STATION
             * @enum {string}
             */
            type: "FIRE_STATION" | "EQUIPMENT_DEPOT" | "TRAINING_CENTER";
        };
        UpdateLocationRequest: {
            /** @example Hauptwache */
            name?: string;
            /** @example Hauptstraße 1, 50667 Köln */
            address?: string;
            /**
             * @example FIRE_STATION
             * @enum {string}
             */
            type?: "FIRE_STATION" | "EQUIPMENT_DEPOT" | "TRAINING_CENTER";
        };
        MemberLocationAssignmentRequest: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            locationId: string;
        };
    };
    responses: {
        /** @description Ungültige Anfrage oder Validierungsfehler */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentifizierung fehlt oder ist ungültig */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Nutzer ist authentifiziert, aber nicht berechtigt */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ressource nicht gefunden */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Konflikt mit aktuellem Systemzustand */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unerwarteter Serverfehler */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        PageParam: number;
        SizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMembers: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
                locationId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste aller Mitglieder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["MemberResponse"][];
                        page?: components["schemas"]["PaginationMeta"];
                    };
                };
            };
        };
    };
    getMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mitglied gefunden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listLocations: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                size?: components["parameters"]["SizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste aller Standorte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LocationResponse"][];
                        page?: components["schemas"]["PaginationMeta"];
                    };
                };
            };
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description Standort erstellt */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Standort gefunden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationRequest"];
            };
        };
        responses: {
            /** @description Standort aktualisiert */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Standort erfolgreich gelöscht */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    assignMemberToLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberLocationAssignmentRequest"];
            };
        };
        responses: {
            /** @description Mitglied erfolgreich Standort zugewiesen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
