name: Setup Frontend Dependencies
description: Install frontend dependencies

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-node

    - name: Install Frontend Dependencies
      working-directory: frontend
      shell: bash
      run: npm ci --legacy-peer-deps
